### ISSUE TITLE
Further development?

### ISSUE THREAD

**Issue by paultanner** [kmi/node-red-contrib-noble#10]
This seems to be dormant now.  Is there a plan to take this past scanning and into discovery and streaming data into node-red from a BLE peripheral device such as an RFduino?  I have looked for another node-red node that might do this but have not found one.

**Comment by cpedrinaci** [comment]
More advanced features are always more than welcome. From my side I've carried out what I needed for now, so I won't be undertaking that development myself. 

I'm happy, however, to review and incorporate changes you may make. Eventually should you be making major contributions it may also make more sense for you to get write access directly.

**Comment by paultanner** [comment]
Thx @cpedrinaci ,
I have something for a phone (cordova-based) but no immediate need for a node-red version.  Will reopen this if and when that changes.
