### ISSUE TITLE
Unable to start BLE scan. Adapter state: poweredOff

### ISSUE THREAD

**Issue by netcompsys** [kmi/node-red-contrib-noble#2]
I have installed on the current version of node-red 0.10.4 on a raspberry pi 2 under raspbian

When I try to use the node I get the following debug message in node red
"Unable to start BLE scan. Adapter state: poweredOff"

Any advise would be appreciated
kevin

lsusb shows
pi@nodered ~ $ lsusb
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp.
Bus 001 Device 012: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Bus 001 Device 009: ID 05e3:0608 Genesys Logic, Inc. USB-2.0 4-Port HUB
Bus 001 Device 010: ID 0403:fc09 Future Technology Devices International, Ltd Crystalfontz CFA-634 USB LCD
Bus 001 Device 011: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial Port

this is the install record - 
pi@nodered ~/.node-red $ sudo apt-get install libbluetooth-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  libbluetooth-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 118 kB of archives.
After this operation, 350 kB of additional disk space will be used.
Get:1 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libbluetooth-dev armhf 4.99-2 [118 kB]
Fetched 118 kB in 0s (233 kB/s)
Selecting previously unselected package libbluetooth-dev.
(Reading database ... 80312 files and directories currently installed.)
Unpacking libbluetooth-dev (from .../libbluetooth-dev_4.99-2_armhf.deb) ...
Setting up libbluetooth-dev (4.99-2) ...
pi@nodered ~/.node-red $ npm install node-red-contrib-noble
|

> noble@0.3.9 install /home/pi/.node-red/node_modules/node-red-contrib-noble/node_modules/noble
> node install.js

noble install: platform is "linux'
noble install: running node-gyp ...
make: Entering directory '/home/pi/.node-red/node_modules/node-red-contrib-noble/node_modules/noble/build'
  CC(target) Release/obj.target/hci-ble/src/hci-ble.o
  LINK(target) Release/hci-ble
  LINK(target) Release/hci-ble: Finished
  CC(target) Release/obj.target/l2cap-ble/src/l2cap-ble.o
  LINK(target) Release/l2cap-ble
  LINK(target) Release/l2cap-ble: Finished
make: Leaving directory '/home/pi/.node-red/node_modules/node-red-contrib-noble/node_modules/noble/build'
noble install: done
node-red-contrib-noble@0.1.1 node_modules/node-red-contrib-noble
??? noble@0.3.9 (debug@0.7.4)
pi@nodered ~/.node-red $
pi@nodered ~/.node-red $

**Comment by netcompsys** [comment]
So I am a complete noob at linux so had not realised there was no Bluetooth installed so I installed 

sudo apt-get install bluetooth bluez-utils blueman

After a bit I was able to 
pi@nodered ~ $ /etc/init.d/bluetooth status
[ ok ] bluetooth is running.

and

pi@nodered ~ $ hcitool scan
Scanning ...
        90:C1:15:40:81:02       XPERIA U
        C4:73:1E:0D:24:F5       TVBluetooth
pi@nodered ~ $

now node red says

Unable to start BLE scan. Adapter state: unauthorized

kevin

**Comment by netcompsys** [comment]
So i have now reinstalled node-red-contrib-noble as follows

pi@nodered /usr/lib/node_modules/node-red $ sudo npm install node-red-contrib-noble
|

> noble@0.3.10 install /usr/lib/node_modules/node-red/node_modules/node-red-contrib-noble/node_modules/noble
> node install.js

noble install: platform is "linux'
noble install: running node-gyp ...
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/node-red/node_modules/node-red-contrib-noble/node_modules/noble/.node-gyp"
make: Entering directory '/usr/lib/node_modules/node-red/node_modules/node-red-contrib-noble/node_modules/noble/build'
  CC(target) Release/obj.target/hci-ble/src/hci-ble.o
  LINK(target) Release/hci-ble
  LINK(target) Release/hci-ble: Finished
  CC(target) Release/obj.target/l2cap-ble/src/l2cap-ble.o
  CC(target) Release/obj.target/l2cap-ble/src/utility.o
  LINK(target) Release/l2cap-ble
  LINK(target) Release/l2cap-ble: Finished
make: Leaving directory '/usr/lib/node_modules/node-red/node_modules/node-red-contrib-noble/node_modules/noble/build'
noble install: done
node-red-contrib-noble@0.1.1 node_modules/node-red-contrib-noble
??? noble@0.3.10 (debug@0.7.4)
rebooted and checked progress

pi@nodered ~ $ cd  /usr/lib/node_modules/node-red
pi@nodered /usr/lib/node_modules/node-red $

pi@nodered /usr/lib/node_modules/node-red $ lsusb
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp.
Bus 001 Device 004: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Bus 001 Device 005: ID 05e3:0608 Genesys Logic, Inc. USB-2.0 4-Port HUB
Bus 001 Device 006: ID 0403:fc09 Future Technology Devices International, Ltd Crystalfontz CFA-634 USB LCD
Bus 001 Device 007: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial Port
pi@nodered /usr/lib/node_modules/node-red $

pi@nodered /usr/lib/node_modules/node-red $ /etc/init.d/bluetooth status
[ ok ] bluetooth is running.

pi@nodered /usr/lib/node_modules/node-red $  hcitool scan
Scanning ...
        90:C1:15:40:81:02       XPERIA U
pi@nodered /usr/lib/node_modules/node-red $

pi@nodered /usr/lib/node_modules/node-red $
pi@nodered /usr/lib/node_modules/node-red $ find -path '_noble_Release/hci-ble'
./node_modules/node-red-contrib-noble/node_modules/noble/build/Release/hci-ble
pi@nodered /usr/lib/node_modules/node-red $

pi@nodered /usr/lib/node_modules/node-red $ find -path '_noble_Release/hci-ble' -exec sudo setcap -v cap_net_raw+eip '{}' \;
./node_modules/node-red-contrib-noble/node_modules/noble/build/Release/hci-ble: OK

Node Red debug still shows
Unable to start BLE scan. Adapter state: unauthorized

I now seem to have exhausted my knowledge ( not difficult) and research

kevin

**Comment by cpedrinaci** [comment]
Hi,
Could you check which version of 'bluez' you have installed? 
Wheezy is still stuck with a version that does not support BLE devices: you'd need version 5+

To install a more modern version with BLE support you have to follow a few steps.
You have some instructions here for example: 
http://www.elinux.org/RPi_Bluetooth_LE

Let me know how it goes.

**Comment by netcompsys** [comment]
Yes I had Bluez 4.99 installed
tried your suggestion, didnt work initially until i removed the previous version
Repeated the instructions again after that and I can get it to work, but only after issuing the command

hciconfig hci0 up

ie
hciconfig
hci0:   Type: BR/EDR  Bus: USB
        BD Address: 00:1A:7D:DA:71:11  ACL MTU: 310:10  SCO MTU: 64:8
        DOWN
        RX bytes:692 acl:0 sco:0 events:33 errors:0
        TX bytes:358 acl:0 sco:0 commands:29 errors:0

pi@nodered ~ $ sudo hciconfig hci0 up
pi@nodered ~ $ hciconfig
hci0:   Type: BR/EDR  Bus: USB
        BD Address: 00:1A:7D:DA:71:11  ACL MTU: 310:10  SCO MTU: 64:8
        UP RUNNING
        RX bytes:1286 acl:0 sco:0 events:67 errors:0
        TX bytes:746 acl:0 sco:0 commands:63 errors:0

That is to say it has to be started manually at each reboot

After that the node detects my Fitbit Flex wristband no problem, range at least 9 yards

the full message received is as follows

{ "payload": { "peripheralUuid": "c4dc19503c1e", "localName": "Flex" }, "peripheralUuid": "c4dc19503c1e", "localName": "Flex", "detectedAt": 1426192824070, "detectedBy": "nodered", "advertisement": { "localName": "Flex", "txPowerLevel": -6, "serviceData": [ { "uuid": "180a", "data": [ 7, 4 ] } ], "serviceUuids": [ "adabfb006e7d4601bda2bffaa68956ba" ] }, "rssi": -31, "_msgid": "f37e7a7f.0c8188" }

Any ideas how I can get this to start automatically at boot?

Thanks
kevin

**Comment by cpedrinaci** [comment]
You could use an udev rule with this content for example

```
# Start/Stop bluetooth service on device insertion.
SUBSYSTEM=="bluetooth", KERNEL=="hci0", RUN+="/usr/local/bin/hciconfig hci0 up"
```

**Comment by netcompsys** [comment]
I have tried a whole load of different udev rules to get the hci0 adapter to startup on boot without success

So as an alternative I have created a simple flow to run on startup which does the job

[{"id":"184e056a.e7b1fb","type":"exec","command":"sudo hciconfig hci0 up","append":"","useSpawn":"","name":"","x":321,"y":497,"z":"799706a5.8668f8","wires":[[],[],[]]},{"id":"eab900d4.1547","type":"inject","name":"","topic":"","payload":"","payloadType":"none","repeat":"","crontab":"","once":true,"x":96,"y":499,"z":"799706a5.8668f8","wires":[["184e056a.e7b1fb"]]},{"id":"782d9a02.87d264","type":"comment","name":"Get the bluetooth adaptor running on startup","info":"","x":194,"y":446,"z":"799706a5.8668f8","wires":[]}]

It may not be the right way , but it does have the advantage of working...

kevin

**Comment by cpedrinaci** [comment]
That’s also an option indeed. Thanks for reporting it back.
I’m currently using that udev rule and it works here so you may need some further configuration of your system.

In any event the important thing is that hci0 needs to be up for the node to report BLEs.

Carlos
