### ISSUE TITLE
Occasionally finds something but what?

### ISSUE THREAD

**Issue by TotallyInformation** [kmi/node-red-contrib-noble#3]
I'm afraid I'm a BTLE newbie. I was hoping to be able to use node-red-contrib-noble as the basis for detecting BTLE devices nearby but I've hit a few hurdles.

I've clearly managed to get by BT 4/BTLE dongle working on my Raspberry Pi 2 because just very occasionally I'm getting something out of this node - the question is WHAT is triggering it? There doesn't seem to be any data in the output that lets me find out. As far as I can tell, the peripheralUuid is actually assigned by the BTE stack when it discovers something. How can I get from that to a MAC address or something else that will indicate what device it is?

I've also tried using a number of devices that I believe have BTLE capability to deliberately trigger output but it just wont happen. I have a Nokia 835, an iPhone 5, a Microsoft Surface Pro (with it's pen which is certainly BTLE) but none of them seem to trigger anything as far as I can see.

The output I have is always the same so clearly 1 device is being picked up from time to time & I always seem to get 2 outputs close together, they all look like:

``` json
{
    "payload": {
        "peripheralUuid": "42c77200b534"
    },
    "peripheralUuid": "42c77200b534",
    "detectedAt": 1428842683449,
    "detectedBy": "Pi2",
    "advertisement": {
        "manufacturerData": [
            76, 0, 12, 14, 0, 164, 28, 175, 238, 47, 95, 0, 90, 53, 79, 34, 208, 99 
        ],
        "serviceData": [],
        "serviceUuids": []
    },
    "rssi": -93,
    "_msgid": "170e3d53.e8f1c3"
}
```

Any help would be gratefully received.

**Comment by TotallyInformation** [comment]
Seems I spoke too soon about only picking up 1 device! Suddenly I've had a bunch:

```
{ "peripheralUuid": "6e43f9425046" }
{ "peripheralUuid": "541eed52d5c2" }
{ peripheralUuid: '7963c2751a00', localName: undefined }
{ peripheralUuid: '673b6c536510', localName: undefined }
```

I actually wonder if these aren't people outside?! Though I'm in the loft our house is straight off the street with quite a few students around. RSSI values are around -50 to -90

**Comment by mblackstock** [comment]
@TotallyInformation - is this a bug or were you really detecting devices you weren't anticipating?  Reason I ask is that I found the node was sending repeated messages after a number of deploys - see #6.  Perhaps its the same issue?

**Comment by cpedrinaci** [comment]
Note that you may configure the node to repeatedly report previously found devices every time they broadcast their presence. Otherwise you will only get a notification the first time.

I'm closing this for now. Let us know if you face further issues.
